spring:
  profiles:
    include:
      - K42
  datasource:
    url:   jdbc:h2:mem:klink42
    username: klink42-user
    password: klink42-pwd
    driver-class-name: org.h2.Driver

---
  spring:
    profiles: K42
---